/-! PM I ✱84, first macro-lot. Project Gutenberg 78050, pp. 540–543. -/
namespace PM.Architecture.Star84Source
def canonicalSource : String :=
  "https://www.gutenberg.org/files/78050/78050-src/78050-src.htm#Page_540"
def propositionIds : List String :=
  ["84.01", "84.02", "84.03", "84.1", "84.11", "84.12", "84.121",
   "84.13", "84.131", "84.132", "84.133", "84.134", "84.135", "84.14",
   "84.2", "84.21", "84.22", "84.23", "84.24", "84.241", "84.242",
   "84.25", "84.26", "84.28", "84.3", "84.31", "84.32", "84.33",
   "84.34", "84.341", "84.342", "84.35", "84.37", "84.4", "84.41",
   "84.411", "84.412", "84.42", "84.421", "84.422", "84.43", "84.51",
   "84.52", "84.521", "84.522", "84.53", "84.54", "84.55", "84.59",
   "84.6", "84.61", "84.62"]
def verbatimStatements : List String :=
  ["Cls² excl = κ̂(α,β∈κ . α≠β .⊃α,β. α∩β=Λ) Df",
   "Cl exclʻγ = Cls² excl ∩ Clʻγ Df",
   "Cls ex² excl = Cls² excl − ∈̆ʻΛ Df",
   "⊢: κ∈Cls² excl .≡: α,β∈κ . α≠β .⊃α,β. α∩β=Λ",
   "⊢: κ∈Cls² excl .≡: α,β∈κ . E! α∩β .⊃α,β. α=β",
   "⊢: κ∈Cl exclʻγ .≡. κ∈Cls² excl . κ⊂γ",
   "⊢: κ∈Cl exclʻγ .≡: α,β∈κ . E! α∩β .⊃α,β. α=β : κ⊂γ",
   "⊢: κ∈Cls ex² excl .≡. κ∈Cls² excl . Λ∉κ",
   "⊢: κ∈Cls ex² excl .≡: α,β∈κ . α≠β .⊃α,β. α∩β=Λ : Λ∉κ",
   "⊢: κ∈Cls ex² excl .≡: α,β∈κ . E! α∩β .⊃α,β. α=β : Λ∉κ",
   "⊢: κ∈Cls ex² excl .≡: α,β∈κ . E! α∩β .⊃α,β. α=β : α∈κ .⊃α. E!α",
   "⊢:: κ∈Cls ex² excl .≡: α,β∈κ .⊃α,β: E!α . E!β : E!α∩β .⊃. α=β",
   "⊢:: κ∈Cls ex² excl .≡: α,β∈κ .⊃α,β: E!α∩β .≡. α=β",
   "⊢: κ∈Cls² excl .≡. ∈↾κ ∈ Cls→1",
   "⊢. Λ∩Cls ∈ Cls ex² excl", "⊢. 1(Cls) ⊂ Cls² excl",
   "⊢. 1 ∈ Cls ex² excl", "⊢. ιʻα ∈ Cls² excl",
   "⊢: E!α .⊃. ιʻα ∈ Cls ex² excl",
   "⊢. ιʻʻα ∈ Cls ex² excl", "⊢: κ⊂1 .⊃. κ∈Cls ex² excl",
   "⊢: κ∈Cls² excl . λ⊂κ .⊃. λ∈Cls² excl",
   "⊢: κ∈Cls ex² excl . λ⊂κ .⊃. λ∈Cls ex² excl",
   "⊢: κ∈Cl exclʻγ . λ⊂κ . γ⊂δ .⊃. λ∈Cl exclʻδ",
   "⊢: κ∈Cls² excl .⊃. ∈Δʻκ⊂1→1",
   "⊢: κ∈Cls² excl . R∈∈Δʻκ . x∈DʻR .⊃. E!R̆ʻx",
   "⊢: κ∈Cls² excl . R∈∈Δʻκ . x∈DʻR .⊃. x∈R̆ʻx . R̆ʻx∈κ",
   "⊢: κ∈Cls² excl . R∈∈Δʻκ . x∈DʻR .⊃. R̆ʻx=(℩α)(α∈κ.x∈α)",
   "⊢: κ∈Cls² excl . R∈∈Δʻκ .⊃: xRα .≡. x∈α . x∈DʻR . α∈κ",
   "⊢: κ∈Cls² excl . R∈∈Δʻκ .⊃. R=DʻR↿∈↾κ",
   "⊢: κ∈Cls² excl . R∈∈Δʻκ . α∈κ .⊃. ιʻRʻα=α∩DʻR",
   "⊢: κ∈Cls² excl .⊃: R∈∈Δʻκ .≡. R∈1→1 . R⊂∈↾κ . ᗡʻR=ᗡʻ∈↾κ",
   "⊢: κ∈Cls² excl . E!∈Δʻκ .⊃. κ∈Cls ex² excl",
   "⊢: κ∈Cls² excl . R,S∈∈Δʻκ .⊃: DʻR=DʻS .≡. R=S",
   "⊢: κ∈Cls² excl .⊃. D↾∈Δʻκ∈1→1 . Dʻʻ∈Δʻκ sm ∈Δʻκ",
   "⊢: α∈κ .⊃α. μ∩α∈1 : μ⊂sʻκ .⊃. μ∈Dʻʻ∈Δʻκ",
   "⊢: κ∈Cls² excl .⊃. Dʻʻ∈Δʻκ=μ̂{α∈κ .⊃α. μ∩α∈1 : μ⊂sʻκ}",
   "⊢: κ∈Cls² excl . α∈κ . μ∈Dʻʻ∈Δʻκ .⊃. μ−α∈Dʻʻ∈Δʻ(κ−ιʻα)",
   "⊢: α∈κ . x∈α . μ∈Dʻʻ∈Δʻ(κ−ιʻα) .⊃. μ∪ιʻx∈Dʻʻ∈Δʻκ",
   "⊢: κ∈Cls² excl . α∈κ . μ∩α∈1 .⊃: μ−α∈Dʻʻ∈Δʻ(κ−ιʻα) .≡. μ∈Dʻʻ∈Δʻκ",
   "⊢: α,β∈Cls² excl . sʻα=sʻβ .⊃: α⊂Dʻʻ∈Δʻβ .≡. β⊂Dʻʻ∈Δʻα",
   "⊢: R↾κ∈Cls→1 .⊃. R→ʻʻκ∈Cls² excl",
   "⊢: R↾κ∈Cls→1 . κ⊂ᗡʻR .⊃. R→ʻʻκ∈Cls² excl",
   "⊢: R→↾β∈1→1 . R→ʻʻβ∈Cls² excl .⊃. R↾sʻβ∈Cls→1",
   "⊢: R∈1→1 . κ∈Cls² excl .⊃: R→ʻʻκ sm κ",
   "⊢: R∈Cls→1 . κ∈Cls² excl .⊃. Rʻʻʻκ∈Cls² excl",
   "⊢: R∈1→Cls . κ∈Cls² excl .⊃. R̆ʻʻʻκ∈Cls² excl",
   "⊢. PΔʻʻκ∈Cls² excl",
   "⊢: κ∪λ∈Cls² excl .≡. κ,λ∈Cls² excl . sʻ(κ−λ)∩sʻλ=Λ",
   "⊢: κ∩λ=Λ .⊃: κ∪λ∈Cls² excl .≡. κ,λ∈Cls² excl . sʻκ∩sʻλ=Λ",
   "⊢: β∉κ .⊃: κ∪ιʻβ∈Cls² excl .≡. κ∈Cls² excl . β∩sʻκ=Λ",
   "⊢: α≠β .⊃: ιʻα∪ιʻβ∈Cls² excl .≡. α∩β=Λ"]
end PM.Architecture.Star84Source
