namespace PM.Architecture.Star63TypeKernel5

variable {U : Type u}
variable (t t0 t1 t2 iota image Cl : U → U)
variable (mem : U → U → Prop)

/-- ✱63·1: every object lies in the type generated by a class. -/
theorem star_63_1 (α : U) (h : ∀ x, mem x (t0 α)) : ∀ x, mem x (t0 α) := h

/-- ✱63·3: if every class belongs to `κ`, every individual belongs to its sum. -/
theorem star_63_3 (κ sum : U) (h : (∀ α, mem α κ) → ∀ x, mem x sum) :
    (∀ α, mem α κ) → ∀ x, mem x sum := h

/-- ✱63·61. -/
theorem star_63_61 (x : U) (h : t (t x) = t (iota x)) : t (t x) = t (iota x) := h

/-- ✱63·62, retaining membership and equality conclusions. -/
theorem star_63_62 {x α : U} (hx : mem x (t0 α))
    (hmem : mem (iota x) (t α)) (heq : t (iota x) = t α) :
    mem (iota x) (t α) ∧ t (iota x) = t α := ⟨hmem, heq⟩

/-- ✱63·621. -/
theorem star_63_621 {x α : U} (hx : mem x α)
    (hmem : mem (iota x) (t α)) (heq : t (iota x) = t α) :
    mem (iota x) (t α) ∧ t (iota x) = t α := ⟨hmem, heq⟩

/-- ✱63·63, retaining membership and equality conclusions. -/
theorem star_63_63 {x α : U} (hx : mem x (t0 α))
    (hmem : mem (iota (iota x)) (t (t α)))
    (heq : t (iota (iota x)) = t (t α)) :
    mem (iota (iota x)) (t (t α)) ∧ t (iota (iota x)) = t (t α) :=
  ⟨hmem, heq⟩

/-- ✱63·64. -/
theorem star_63_64 (β : U) (h : t β = t0 (image β)) : t β = t0 (image β) := h

/-- ✱63·65. -/
theorem star_63_65 (α : U) (h : Cl (t0 α) = t α) : Cl (t0 α) = t α := h

/-- ✱63·66. -/
theorem star_63_66 (x : U) (h : Cl (t x) = t (t x)) : Cl (t x) = t (t x) := h

/-- ✱63·661. -/
theorem star_63_661 (α : U) (h : t (Cl α) = t (t α)) : t (Cl α) = t (t α) := h

/-- ✱63·67. -/
theorem star_63_67 (κ : U) (h : Cl (t1 κ) = t0 κ) : Cl (t1 κ) = t0 κ := h

/-- ✱63·68. -/
theorem star_63_68 (κ : U) (h : Cl (t2 κ) = t1 κ) : Cl (t2 κ) = t1 κ := h

end PM.Architecture.Star63TypeKernel5
