/-!
# PM I ✱97 — families generated by a relation, first macro-lot

Canonical Gutenberg 78050, volume I pp. 654–658. Inventory: ✱97·01, ·1,
·101, ·11, ·111, ·12, ·13, ·14, ·15, ·16, ·17, ·18, ·2, ·21, ·22,
·23, ·231, ·24.  PM's double-arrow is the symmetric neighbourhood
generated by a relation; the kernel records its extensional content.
-/
namespace PM.Architecture.Star97Source
def canonicalSource : String :=
  "https://www.gutenberg.org/files/78050/78050-src/78050-src.htm#Page_654"
def propositionIds : List String :=
  ["97.01","97.1","97.101","97.11","97.111","97.12","97.13","97.14",
   "97.15","97.16","97.17","97.18","97.2","97.21","97.22","97.23",
   "97.231","97.24"]
end PM.Architecture.Star97Source
