import Principia.Syntax.Formula
import Principia.Syntax.Ramified
import Principia.Deduction.Star11Derived
import Principia.Deduction.Star10Derived
import Principia.Deduction.Star14Derived
import Principia.Deduction.Star20Derived
import Principia.Deduction.Star21Derived
import Principia.Deduction.Star22Derived
import Principia.Deduction.Star24Derived
import Principia.Deduction.Star25Derived
import Principia.Deduction.Star30Derived
import Principia.Deduction.Star33Derived
import Principia.Deduction.Star34Derived
import Principia.Deduction.Star35Derived
import Principia.Deduction.Star40Derived
import Principia.Deduction.Star41Derived
import Principia.Deduction.Star50Derived
import Principia.Deduction.Star52Derived
import Principia.Syntax.Apparent
import Principia.Syntax.Printed
import Principia.Syntax.Description
import Principia.Syntax.DescriptionDefinitions
import Principia.Deduction.System
import Principia.Deduction.Star9
import Principia.Deduction.Star11
import Principia.Deduction.Star10
import Principia.Experimental.RamifiedToy
import Principia.Experimental.TypicalAmbiguityToy
import Principia.Experimental.DescriptionScopeToy
import Principia.Experimental.ElementaryFormationToy
import Principia.Experimental.PredicativeGateToy
import Principia.Experimental.UnifiedSyntaxEnvelope
import Principia.FirstEdition.Volume1.Star23Source
import Principia.FirstEdition.Volume1.Star30Source
import Principia.FirstEdition.Volume1.Star37Source
import Principia.FirstEdition.Volume1.Star40Source
import Principia.FirstEdition.Volume1.Star41Source
import Principia.FirstEdition.Volume1.Star42Source
import Principia.FirstEdition.Volume1.Star43Source
import Principia.FirstEdition.Volume1.Star50Source
import Principia.FirstEdition.Volume1.Star51Source
import Principia.FirstEdition.Volume1.Star52Source
import Principia.FirstEdition.Volume1.Star53Source
import Principia.FirstEdition.Volume1.Star54Source
import Principia.FirstEdition.Volume1.Star55Source
import Principia.FirstEdition.Volume1.Star60Source
import Principia.FirstEdition.Volume1.Star61Source
import Principia.FirstEdition.Volume1.Star62Source
import Principia.FirstEdition.Volume1.Star63Source
import Principia.FirstEdition.Volume1.Star64Source
import Principia.FirstEdition.Volume1.Star65Source
import Principia.FirstEdition.Volume1.Star70
import Principia.FirstEdition.Volume1.Star80Source
import Principia.FirstEdition.Volume1.Star81Source
import Principia.FirstEdition.Volume1.Star82Source
import Principia.FirstEdition.Volume1.Star82Kernel
import Principia.FirstEdition.Volume1.Star82Kernel2
import Principia.FirstEdition.Volume1.Star72Source
import Principia.FirstEdition.Volume1.Star73Source
import Principia.FirstEdition.Volume1.Star85Source
import Principia.FirstEdition.Volume1.Star85Kernel
import Principia.FirstEdition.Volume1.Star85Kernel2
import Principia.FirstEdition.Volume1.Star85Kernel3
import Principia.FirstEdition.Volume1.Star88Source
import Principia.FirstEdition.Volume1.Star90Source
import Principia.FirstEdition.Volume1.Star91Source
import Principia.FirstEdition.Volume1.Star92Source
import Principia.FirstEdition.Volume1.Star93Source
import Principia.FirstEdition.Volume1.Star94Source
import Principia.FirstEdition.Volume1.Star95Source
import Principia.FirstEdition.Volume1.Star95Kernel
import Principia.FirstEdition.Volume1.Star95Kernel2
import Principia.FirstEdition.Volume1.Star95Kernel3
import Principia.FirstEdition.Volume1.Star95Kernel4
import Principia.FirstEdition.Volume1.Star96Source
import Principia.FirstEdition.Volume1.Star97Source
import Principia.FirstEdition.Volume2.Star100Source
import Principia.FirstEdition.Volume2.Star101Source
import Principia.FirstEdition.Volume2.Star102Source
import Principia.FirstEdition.Volume2.Star103Source
import Principia.FirstEdition.Volume2.Star103Kernel
import Principia.FirstEdition.Volume2.Star103Kernel2
import Principia.FirstEdition.Volume2.Star105Source
import Principia.FirstEdition.Volume2.Star106Source
import Principia.FirstEdition.Volume2.Star110Source
import Principia.FirstEdition.Volume2.Star110Kernel
import Principia.FirstEdition.Volume2.Star110Kernel2
import Principia.FirstEdition.Volume2.Star110Kernel3
import Principia.FirstEdition.Volume2.Star110Kernel4
import Principia.FirstEdition.Volume2.Star110Kernel5
import Principia.FirstEdition.Volume2.Star111Source
import Principia.FirstEdition.Volume2.Star112Source
import Principia.FirstEdition.Volume2.Star113Source
import Principia.FirstEdition.Volume2.Star114Source
import Principia.FirstEdition.Volume2.Star115Source
import Principia.FirstEdition.Volume2.Star116Source
import Principia.FirstEdition.Volume2.Star117Source
import Principia.FirstEdition.Volume2.Star118Source
import Principia.FirstEdition.Volume2.Star119Source
import Principia.FirstEdition.Volume2.Star120Source
import Principia.FirstEdition.Volume2.Star121Source
import Principia.FirstEdition.Volume2.Star123Source
import Principia.FirstEdition.Volume2.Star124Source
import Principia.FirstEdition.Volume2.Star125Source
import Principia.FirstEdition.Volume2.Star126Source
import Principia.FirstEdition.Volume2.Star200Source
import Principia.FirstEdition.Volume2.Star202Source
import Principia.FirstEdition.Volume2.Star202Kernel
import Principia.FirstEdition.Volume2.Star202Kernel2
import Principia.FirstEdition.Volume2.Star202Kernel3
import Principia.FirstEdition.Volume2.Star202Kernel4
import Principia.FirstEdition.Volume2.Star205Source
import Principia.FirstEdition.Volume2.Star207Source
import Principia.FirstEdition.Volume2.Star210Source
import Principia.FirstEdition.Volume2.Star211Source
import Principia.FirstEdition.Volume2.Star211Kernel
import Principia.FirstEdition.Volume2.Star211Kernel2
import Principia.FirstEdition.Volume2.Star211Kernel3
import Principia.FirstEdition.Volume2.Star211Kernel4
import Principia.FirstEdition.Volume2.Star211Kernel5
import Principia.FirstEdition.Volume2.Star211Kernel6
import Principia.FirstEdition.Volume2.Star211Kernel7
import Principia.FirstEdition.Volume2.Star211Kernel8
import Principia.FirstEdition.Volume2.Star212Source
import Principia.FirstEdition.Volume2.Star214Source
import Principia.FirstEdition.Volume3.Star215Source
import Principia.SecondEdition.Volume2.Star216Source
import Principia.SecondEdition.Volume2.Star217Source
import Principia.FirstEdition.Volume2.Star230Source
import Principia.FirstEdition.Volume2.Star231Source
import Principia.FirstEdition.Volume2.Star233Source
import Principia.FirstEdition.Volume2.Star232Source
import Principia.FirstEdition.Volume3.Star234Source
import Principia.FirstEdition.Volume3.Star250Source
import Principia.FirstEdition.Volume3.Star250OpeningKernel
import Principia.FirstEdition.Volume3.Star250NextKernel
import Principia.FirstEdition.Volume3.Star250ThirdKernel
import Principia.FirstEdition.Volume3.Star250FinalKernel
import Principia.FirstEdition.Volume3.Star256Source
import Principia.FirstEdition.Volume1.Star64Source
import Principia.FirstEdition.Volume1.Introduction
import Principia.FirstEdition.Volume1.Part1.SectionA.Star1
import Principia.FirstEdition.Volume1.Part1.SectionA.Star2
import Principia.FirstEdition.Volume1.Part1.SectionA.Star3
import Principia.FirstEdition.Volume1.Part1.SectionA.Star4
import Principia.FirstEdition.Volume1.Part1.SectionA.Star5Kernel
import Principia.FirstEdition.Volume1.Star9
import Principia.FirstEdition.Volume1.Star14

-- Modules holding catalogued declarations that no other module imported, so
-- `lake build` compiled them (via lakefile globs) but `import Principia` could not
-- reach them: `#print axioms` was blind to them and they were outside the
-- published library.  Criterion T1 requires import-closure membership.
import Principia.FirstEdition.Volume1.Part1.SectionA.Star5Q245
import Principia.FirstEdition.Volume1.Part1.SectionA.Star5Q246
import Principia.FirstEdition.Volume1.Part1.SectionA.Star5Q247
import Principia.Deduction.PrintedNames
import Principia.FirstEdition.Volume2.Star150Source
import Principia.FirstEdition.Volume2.Star151Source
import Principia.FirstEdition.Volume2.Star152Source
import Principia.FirstEdition.Volume2.Star153Source
import Principia.FirstEdition.Volume2.Star154Source
import Principia.FirstEdition.Volume2.Star155Source
import Principia.FirstEdition.Volume2.Star160Source
import Principia.FirstEdition.Volume2.Star161Source
import Principia.FirstEdition.Volume2.Star162Source
import Principia.FirstEdition.Volume2.Star163Source
import Principia.FirstEdition.Volume2.Star164Source
import Principia.FirstEdition.Volume2.Star165Source
import Principia.FirstEdition.Volume2.Star166Source
import Principia.FirstEdition.Volume2.Star170Source
import Principia.FirstEdition.Volume2.Star171Source
import Principia.FirstEdition.Volume2.Star172Source
import Principia.FirstEdition.Volume2.Star173Source
import Principia.FirstEdition.Volume2.Star174Source
import Principia.FirstEdition.Volume2.Star176Source
import Principia.FirstEdition.Volume2.Star177Source
import Principia.FirstEdition.Volume2.Star180Source
import Principia.FirstEdition.Volume2.Star181Source
import Principia.FirstEdition.Volume2.Star183Source
import Principia.FirstEdition.Volume2.Star184Source
import Principia.FirstEdition.Volume2.Star185Source
import Principia.FirstEdition.Volume2.Star186Source
import Principia.Deduction.Star51Derived
import Principia.Deduction.Star54Derived
import Principia.Deduction.Star55Derived
import Principia.Deduction.Star60Derived
import Principia.Deduction.Star62Derived
import Principia.Deduction.Star91Derived
import Principia.Deduction.Star93Derived
import Principia.Deduction.Star96Derived
import Principia.Deduction.Star97Derived
import Principia.Deduction.Star100Derived
import Principia.Deduction.Star102Derived
import Principia.Deduction.Star105Derived
import Principia.Deduction.Star106Derived
import Principia.Deduction.Star111Derived
import Principia.Deduction.Star112Derived
import Principia.Deduction.Star121Derived
import Principia.Deduction.Star123Derived
import Principia.Deduction.Star215Derived
import Principia.Deduction.Star216Derived
