/- Non-repository opaque interface. Do not promote or import into the repository.
   Exact target declarations are in the paired manifest/prompt; dependencies below are stubs only. -/

-- OPAQUE-PM-DEPENDENCY PM1:✱1·6
-- OPAQUE-PM-DEPENDENCY PM1:✱2·11
-- OPAQUE-PM-DEPENDENCY PM1:✱2·53
-- OPAQUE-PM-DEPENDENCY PM1:✱2·54
-- OPAQUE-PM-DEPENDENCY PM1:✱3·2
-- OPAQUE-PM-DEPENDENCY PM1:✱3·21
-- OPAQUE-PM-DEPENDENCY PM1:✱3·26
-- OPAQUE-PM-DEPENDENCY PM1:✱3·27
-- OPAQUE-PM-DEPENDENCY PM1:✱3·31
-- OPAQUE-PM-DEPENDENCY PM1:✱3·43
-- OPAQUE-PM-DEPENDENCY PM1:✱3·44
-- OPAQUE-PM-DEPENDENCY PM1:✱3·47
-- OPAQUE-PM-DEPENDENCY PM1:✱3·48
-- OPAQUE-PM-DEPENDENCY PM1:✱4·01
