/- Non-repository opaque interface. Do not promote or import into the repository.
   Exact target declarations are in the paired manifest/prompt; dependencies below are stubs only. -/

-- OPAQUE-PM-DEPENDENCY PM1:✱2·05
-- OPAQUE-PM-DEPENDENCY PM1:✱2·06
-- OPAQUE-PM-DEPENDENCY PM1:✱2·08
-- OPAQUE-PM-DEPENDENCY PM1:✱3·21
-- OPAQUE-PM-DEPENDENCY PM1:✱3·26
-- OPAQUE-PM-DEPENDENCY PM1:✱3·27
-- OPAQUE-PM-DEPENDENCY PM1:✱3·3
-- OPAQUE-PM-DEPENDENCY PM1:✱3·43
-- OPAQUE-PM-DEPENDENCY PM1:✱4·01
-- OPAQUE-PM-DEPENDENCY PM1:✱4·1
-- OPAQUE-PM-DEPENDENCY PM1:✱4·12
-- OPAQUE-PM-DEPENDENCY PM1:✱4·22
-- OPAQUE-PM-DEPENDENCY PM1:✱4·31
-- OPAQUE-PM-DEPENDENCY PM1:✱4·57
