/- Non-repository opaque interface. Do not promote or import into the repository.
   Exact target declarations are in the paired manifest/prompt; dependencies below are stubs only. -/

-- OPAQUE-PM-DEPENDENCY PM1:✱1·01
-- OPAQUE-PM-DEPENDENCY PM1:✱2·01
-- OPAQUE-PM-DEPENDENCY PM1:✱2·05
-- OPAQUE-PM-DEPENDENCY PM1:✱2·06
-- OPAQUE-PM-DEPENDENCY PM1:✱2·08
-- OPAQUE-PM-DEPENDENCY PM1:✱2·16
-- OPAQUE-PM-DEPENDENCY PM1:✱2·17
-- OPAQUE-PM-DEPENDENCY PM1:✱2·54
-- OPAQUE-PM-DEPENDENCY PM1:✱3·26
-- OPAQUE-PM-DEPENDENCY PM1:✱3·27
-- OPAQUE-PM-DEPENDENCY PM1:✱3·3
-- OPAQUE-PM-DEPENDENCY PM1:✱3·43
-- OPAQUE-PM-DEPENDENCY PM1:✱4·01
-- OPAQUE-PM-DEPENDENCY PM1:✱4·12
-- OPAQUE-PM-DEPENDENCY PM1:✱4·21
-- OPAQUE-PM-DEPENDENCY PM1:✱4·38
-- OPAQUE-PM-DEPENDENCY PM1:✱4·41
-- OPAQUE-PM-DEPENDENCY PM1:✱4·51
-- OPAQUE-PM-DEPENDENCY PM1:✱4·61
-- OPAQUE-PM-DEPENDENCY PM1:✱4·63
-- OPAQUE-PM-DEPENDENCY PM1:✱4·64
-- OPAQUE-PM-DEPENDENCY PM1:✱4·65
-- OPAQUE-PM-DEPENDENCY PM1:✱4·82
-- OPAQUE-PM-DEPENDENCY PM1:✱5·1
