namespace PM.FirstEdition.Volume1.Introduction.Chapter3

/-! # Chapter III, pages 79–88

Canonical edition: first edition, volume I (1910), pp. 79–88, scan leaves
101–110. This scan-collated verbal-diplomatic reflow concludes the chapter.
Page-local notes 33–37 are independent canonical blocks. Printed and digital
variants are recorded in the external critical apparatus and do not alter the
canonical first-impression bytes below.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-CLASS-DEFINITION-REQUISITES-PP79-81A
such a case what is symbolically, though not really, the same function \(f\) can receive as arguments functions of various different types. If, with a given argument \(\phi \hat{z}\), the function \(f(\phi \hat{z}\)), so interpreted, is equivalent to \(f(\psi !\hat{z}\)) whenever \(\psi ! \hat{z}\) is formally equivalent to \(\phi \hat{z}\), then \(f\{\hat{z}(\phi z)\}\) is equivalent to \(f(\phi \hat{z}\)) provided there is any predicative function formally equivalent to \(\phi \hat{z}\). At this point, we make use of the axiom of reducibility, according to which there always is a predicative function formally equivalent to \(\phi \hat{z}\).
As was explained above, it is convenient to regard an extensional function of a function as having for its argument not the function, but the class determined by the function. Now we have seen that our derived function is always extensional. Hence if our original function was \(f(\psi !\hat{z}\)), we write the derived function \(f\{\hat{z}(\phi z)\}\), where "\(\hat{z}(\phi z\))" may be read "the class of arguments which satisfy \(\phi \hat{z}\)," or more simply "the class determined by \(\phi \hat{z}\)." Thus "\(f\{\hat{z}(\phi z)\}\)" will mean: "There is a predicative function \(\psi !\hat{z}\) which is formally equivalent to \(\phi \hat{z}\) and is such that \(f(\psi !\hat{z}\)) is true." This is in reality a function of \(\phi \hat{z}\), but we treat it symbolically as if it had an argument \(\hat{z}(\phi z\)). By the help of the axiom of reducibility, we find that the usual properties of classes result. For example, two formally equivalent functions determine the same class, and conversely, two functions which determine the same class are formally equivalent. Also to say that \(x\) is a member of \(\hat{z}(\phi z\)), i.e. of the class determined by \(\phi \hat{z}\), is true when \(\phi x\) is true, and false when \(\phi x\) is false. Thus all the mathematical purposes for which classes might seem to be required are fulfilled by the purely symbolic objects \(\hat{z}(\phi z\)) provided we assume the axiom of reducibility.
In virtue of the axiom of reducibility, if \(\phi \hat{z}\) is any function, there is a formally equivalent predicative function \(\psi ! \hat{z}\); then the class \(\hat{z}(\phi z\)) is identical with the class \(\hat{z}(\psi !z\)), so that every class can be defined by a predicative function. Hence the totality of the classes to which a given term can be significantly said to belong or not to belong is a legitimate totality, although the totality of functions which a given term can be significantly said to satisfy or not to satisfy is not a legitimate totality. The classes to which a given term \(a\) belongs or does not belong are the classes defined by \(a\)-functions; they are also the classes defined by predicative \(a\)-functions. Let us call them \(a\)-classes. Then "\(a\)-classes" form a legitimate totality, derived from that of predicative \(a\)-functions. Hence many kinds of general statements become possible which would otherwise involve vicious-circle paradoxes. These general statements are none of them such as lead to contradictions, and many of them such as it is very hard to suppose illegitimate. The fact that they are rendered possible by the axiom of reducibility, and that they would otherwise be excluded by the vicious-circle principle, is to be regarded as an argument in favour of the axiom of reducibility.
The above definition of "the class defined by the function \(\phi\hat{z}\)," or rather, of any proposition in which this phrase occurs, is, in symbols, as follows: \[ f{\hat{z}(\phi z)}.=\colon(\exists \psi)\colon \phi x.\equiv_{x}.\psi !x\colon f\{\psi !\hat{z}\}\,\quad \text{Df}. \] In order to recommend this definition, we shall enumerate five requisites which a definition of classes must satisfy, and we shall then show that the above definition satisfies these five requisites.
We require of classes, if they are to serve the purposes for which they are commonly employed, that they shall have certain properties, which may be enumerated as follows. (1) Every propositional function must determine a class, which may be regarded as the collection of all the arguments satisfying the function in question. This principle must hold when the function is satisfied by an infinite number of arguments as well as when it is satisfied by a finite number. It must hold also when no arguments satisfy the function; i.e. the "null-class" must be just as good a class as any other. (2) Two propositional functions which are formally equivalent, i.e. such that any argument which satisfies either satisfies the other, must determine the same class; that is to say, a class must be something wholly determined by its membership, so that e.g. the class "featherless bipeds" is identical with the class "men," and the class "even primes" is identical with the class "numbers identical with 2." (3) Conversely, two propositional functions which determine the same class must be formally equivalent; in other words, when the class is given, the membership is determinate: two different sets of objects cannot yield the same class. (4) In the same sense in which there are classes (whatever this sense may be), or in some closely analogous sense, there must also be classes of classes. Thus for example "the combinations of \(n\) things \(m\) at a time," where the \(n\) things form a given class, is a class of classes; each combination of \(m\) things is a class, and each such class is a member of the specified set of combinations, which set is therefore a class whose members are classes. Again, the class of unit classes, or of couples, is absolutely indispensable; the former is the number 1, the latter the number 2. Thus without classes of classes, arithmetic becomes impossible. (5) It must under all circumstances be meaningless to suppose a class identical with one of its own members. For if such a supposition had any meaning, "\(\alpha \in \alpha\)" would be a significant propositional function, and so would "\(\alpha \sim{\in \alpha}\)." Hence, by (1) and (4), there would be a class of all classes satisfying the function "\(\alpha \sim{\in \alpha}\)." If we call this class \(\kappa\), we shall have \[ \alpha \in \kappa.\equiv_{\alpha}. \alpha \sim{\in \alpha}. \] Since, by our hypothesis, "\(\kappa \in \kappa\)" is supposed significant, the above equivalence, which holds with all possible values of \(\alpha\), holds with the value \(\kappa\), i.e. \[ \kappa \in \kappa.\equiv. \kappa \sim{\in \kappa}. \]
But this is a contradiction. Hence "\(\alpha \in \alpha\)" and "\(\alpha \sim{\in \alpha}\)" must always be meaningless. In general, there is nothing surprising about this conclusion, but it has two consequences which deserve special notice. In the first place, a class consisting of only one member must not be identical with that one member, i.e. we must not have \(\iota ʻx=x\). For we have \(x \in \iota ʻx\), and therefore, if \(x = \iota ʻx\), we have \(\iota ʻx \in \iota ʻx\), which, we saw, must be meaningless. It follows that "\(x = \iota ʻx\)" must be absolutely meaningless, not simply false. In the second place, it might appear as if the class of all classes were a class, i.e. as if (writing "Cls" for "class") "\(\text{Cls}\,\in\, \text{Cls}\)" were a true proposition. But this combination of symbols must be meaningless; unless, indeed, an ambiguity exists in the meaning of "Cls," so that, in "\(\text{Cls}\, \in\, \text{Cls}\)," the first "Cls" can be supposed to have a different meaning from the second.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-CLASS-DEFINITION-REQUISITES-PP79-81A -/

/- PM-FORMAL-GLOSS
This source-critical historical prose introduces no Lean declaration.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-CLASS-CONSEQUENCES-PP81B-84
As regards the above requisites, it is plain, to begin with, that, in accordance with our definition, every propositional function \(\phi \hat{z}\) determines a class \(\hat{z}(\phi z\)). Assuming the axiom of reducibility, there must always be true propositions about \(\hat{z}(\phi z\)), i.e. true propositions of the form \(f\{\hat{z}(\phi z)\}\). For suppose \(\phi \hat{z}\) is formally equivalent to \(\psi !\hat{z}\), and suppose \(\psi !\hat{z}\) satisfies some function \(f\). Then \(\hat{z}(\phi z\)) also satisfies \(f\). Hence, given any function \(\phi \hat{z}\), there are true propositions of the form \(f\{\hat{z}(\phi z)\}\), i.e. true propositions in which "the class determined by \(\phi \hat{z}\)" is grammatically the subject. This shows that our definition fulfils the first of our five requisites.
The second and third requisites together demand that the classes \(\hat{z}(\phi z\)) and \(\hat{z}(\psi z\)) should be identical when, and only when, their defining functions are formally equivalent, i.e. that we should have \[ \hat{z}(\phi z)=\hat{z}(\psi z).\equiv\colon \phi x.\equiv_{x}.\psi x. \] Here the meaning of "\(\hat{z}(\phi z)\) = \(\hat{z}(\psi z)\)" is to be derived, by means of a two-fold application of the definition of \(f\{\hat{z}(\phi z)\}\), from the definition of \[ “\chi !\hat{z} = \theta!\hat{z}, ” \] \[ \text{which is}\quad \chi !\hat{z}= \theta!\hat{z}.=\colon (f)\colon f!\chi !\hat{z}.\supset.f!\theta !\hat{z}\, \quad\text{Df} \] by the general definition of identity.
In interpreting "\(\hat{z}(\phi z) = \hat{z}(\psi z)\)," we will adopt the convention which we adopted in regard to (\({℩}x)(\phi x\)) and (\({℩}x)(\psi x)\), namely that the incomplete symbol which occurs first is to have the larger scope. Thus \(\hat{z}(\phi z) = \hat{z}(\psi z)\) becomes, by our definition, \[ (\exists \chi) \colon \phi x . \equiv_{x} . \chi !x \colon \chi ! \hat{z} = \hat{z}(\psi z), \] which, by eliminating \(\hat{z}(\psi z\)), becomes \[ (\exists \chi) \colon\ldotp \phi x.\equiv_{x}.\chi !x \colon\ldotp (\exists \theta)\colon \psi x.\equiv_{x}.\theta !x\colon \chi !\hat{z} = \theta !\hat{z}, \] which is equivalent to \[ (\exists \chi , \theta)\colon \phi x.\equiv_{x}.\chi !x\colon \psi x.\equiv_{x}. \theta !x\colon \chi !\hat{z} = \theta !\hat{z}, \]
which, again, is equivalent to \[ (\exists \chi) \colon \phi x \ldotp \equiv_{x} \ldotp \chi!x \colon \psi x \ldotp \equiv_{x} \ldotp \chi!x, \] which, in virtue of the axiom of reducibility, is equivalent to \[ \phi x \ldotp \equiv_{x} \ldotp \psi x. \] Thus our definition of the use of \(\hat{z}(\phi z)\) is such as to satisfy the conditions (2) and (3) which we laid down for classes, i.e. we have \[ \vdash \colon\ldotp \hat{z}(\phi z) = \hat{z}(\psi z) \ldotp \equiv \colon \phi x \ldotp \equiv_{x} \ldotp \psi x. \]
Before considering classes of classes, it will be well to define membership of a class, i.e. to define the symbol "\(x \in\hat{z} (\phi z)\)," which may be read "\(x\) is a member of the class determined by \(\phi\hat{z}\)." Since this is a function of the form \(f\{\hat{z}(\phi z)\}\), it must be derived, by means of our general definition of such functions, from the corresponding function \(f\{\psi!\hat{z}\}\). We therefore put \[ x \in \psi!\hat{z} \ldotp = \ldotp \psi!x \quad\text{Df}. \] This definition is only needed in order to give a meaning to "\(x\in \hat{z}(\phi z)\)"; the meaning it gives is, in virtue of the definition of \(f\{\hat{z}(\phi z)\}\), \[ (\exists\psi) \colon \phi y \ldotp \equiv_{y} \ldotp \psi!y \colon \psi!x. \] It thus appears that "\(x \in \hat{z}(\phi z)\)" implies \(\phi x\), since it implies \(\psi!x\), and \(\psi!x\) is equivalent to \(\phi x\); also, in virtue of the axiom of reducibility, \(\phi x\) implies "\(x \in \hat{z}(\phi z)\)," since there is a predicative function \(\psi\) formally equivalent to \(\phi\), and \(x\) must satisfy \(\psi\), since \(x\) (ex hypothesi) satisfies \(\phi\). Thus in virtue of the axiom of reducibility we have \[ \vdash \colon x \in \hat{z}(\phi z) \ldotp \equiv \ldotp \phi x, \] i.e. \(x\) is a member of the class \(\hat{z}(\phi z)\) when, and only when, \(x\) satisfies the function \(\phi\) which defines the class.
We have next to consider how to interpret a class of classes. As we have defined \(f\{\hat{z}(\phi z)\}\), we shall naturally regard a class of classes as consisting of those values of \(\hat{z}(\phi z)\) which satisfy \(f\{\hat{z}(\phi z)\}\). Let us write \(\alpha\) for \(\hat{z}(\phi z)\); then we may write \(\hat{\alpha}(f\alpha)\) for the class of values of \(\alpha\) which satisfy \(f\alpha\). We shall apply the same definition, and put \[ F\{\hat{\alpha}(f\alpha)\} \ldotp = \colon (\exists g) \colon f\beta \ldotp \equiv_{\beta} \ldotp g!\beta \colon F\{g!\hat{\alpha}\} \quad \text{Df}, \] where "\(\beta\)" stands for any expression of the form \(\hat{z}(\psi!z)\).
Let us take "\(\gamma \in \hat{\alpha}(f\alpha)\)" as an instance of \(F\{\hat{\alpha}(f\alpha)\}\). Then \[ \vdash \colon\ldotp \gamma \in \hat{\alpha} (f\alpha) \ldotp \equiv \colon (\exists g) : f\beta \ldotp \equiv_{\beta} \ldotp g!\beta \colon \gamma\in g!\hat{\alpha}. \] Just as we put \[ x \in\psi! \hat{z} \ldotp = \ldotp \psi!x \quad \text{Df}, \] so we put \[ \gamma \in g! \hat{\alpha} \ldotp = \ldotp g!\gamma \quad \text{Df}. \]
Thus we find \[ \vdash \colon\ldotp \gamma \in \hat{\alpha} (f\alpha) \ldotp \equiv : (\exists g) : f\beta \ldotp \equiv_{\beta} \ldotp g!\beta : g!\gamma. \]
If we now extend the axiom of reducibility so as to apply to functions of functions, i.e. if we assume \[ (\exists g)\colon f(\psi !\hat{z}).\equiv_{\psi}.g!(\psi !\hat{z}), \] we easily deduce \[ \begin{array}{l} &\vdash\colon(\exists g)\colon f{\{\hat{z}(\psi !z)\}}.\equiv_{\psi}.g!\{\hat{z}(\psi !z)\},\\ \textit{i.e.}\quad &\vdash\colon(\exists g)\colon f \beta .\equiv_{\beta}.g!\beta.\\ \text{Thus}\quad &\vdash \colon \gamma \in \hat{\alpha}(f \alpha).\equiv.f \gamma. \end{array} \]
Thus every function which can take classes as arguments, i.e. every function of functions, determines a class of classes, whose members are those classes which satisfy the determining function. Thus the theory of classes of classes offers no difficulty.
We have next to consider our fifth requisite, namely that "\(\hat{z}(\phi z)\in \hat{z}(\phi z\))" is to be meaningless. Applying our definition of \(f\{\hat{z}(\phi z)\}\), we find that if this collection of symbols had a meaning, it would mean \[ (\exists \psi)\colon \phi x.\equiv_{x}. \psi!x \colon \psi !\hat{z} \in \psi !\hat{z}, \] i.e. in virtue of the definition \[ \begin{array}{l} &x \in \psi!\hat{z}.=. \psi !x \quad \text{Df},\\ \text{it would mean}\quad &(\exists \psi)\colon \phi x.\equiv_{x}. \psi!x\colon \psi !(\psi !\hat{z}). \end{array} \] But here the symbol "\(\psi!(\psi !\hat{z})\)" occurs, which assigns a function as argument to itself. Such a symbol is always meaningless, for the reasons explained at the beginning of Chapter II (pp. 41-43). Hence "\(\hat{z}(\phi z) \in \hat{z}(\phi z)\)" is meaningless, and our fifth and last requisite is fulfilled.
As in the case of \(f({℩}x)(\phi x\)), so in that of \(f\{\hat{z}(\phi z)\}\), there is an ambiguity as to the scope of \(\hat{z}(\phi z)\) if it occurs in a proposition which itself is part of a larger proposition. But in the case of classes, since we always have the axiom of reducibility, namely \[ (\exists \psi) \colon \phi x.\equiv_{x}.\psi !x, \] which takes the place of \(\text{E}!(℩x)(\phi x)\), it follows that the truth-value of any proposition in which \(\hat{z}(\phi z)\) occurs is the same whatever scope we may give to \(\hat{z}(\phi z)\), provided the proposition is an extensional function of whatever functions it may contain. Hence we may adopt the convention that the scope is to be always the smallest proposition enclosed in dots or brackets in which \(\hat{z}(\phi z)\) occurs. If at any time a larger scope is required, we may indicate it by "[\(\hat{z}(\phi z)\)]" followed by dots, in the same way as we did for \([({℩}x)(\phi x)]\).
Similarly when two class symbols occur, e.g. in a proposition of the form \(f\{\hat{z}(\phi z),\hat{z}(\psi z)\}\), we need not remember rules for the scopes of the two symbols, since all choices give equivalent results, as it is easy to prove. For the preliminary propositions a rule is desirable, so we can decide that the class symbol which occurs first in the order of writing is to have the larger scope.
The representation of a class by a single letter \(\alpha \) can now be understood. For the denotation of \(\alpha \) is ambiguous, in so far as it is undecided as to which of the symbols \(\hat{z}(\phi z)\), \(\hat{z}(\psi z)\), \(\hat{z}(\chi z)\), etc. it is to stand for, where \(\phi \hat{z}\), \(\psi \hat{z}\), \(\chi \hat{z}\), etc. are the various determining functions of the class. According to the choice made, different propositions result. But all the resulting propositions are equivalent by virtue of the easily proved proposition: \[ “\vdash :\phi x\equiv_{x}\psi x.\supset .f\{\hat{z}(\phi z)\}\equiv f\{\hat{z}(\psi z)\}. ” \] Hence unless we wish to discuss the determining function itself, so that the notion of a class is really not properly present, the ambiguity in the denotation of \(\alpha\) is entirely immaterial, though, as we shall see immediately, we are led to limit ourselves to predicative determining functions. Thus "\(f(\alpha)\)," where \(\alpha\) is a variable class, is really "\(f\{\hat{z}(\phi z)\}\)," where \(\phi\) is a variable function, that is, it is \[ “(\exists \psi ).\phi x\equiv_{x}\psi !x.f\{\psi !\hat{z}\}, ” \] where \(\phi\) is a variable function. But here a difficulty arises which is removed by a limitation to our practice and by the axiom of reducibility. For the determining functions \(\phi \hat{z}\), \(\psi \hat{z}\), etc. will be of different types, though the axiom of reducibility secures that some are predicative functions. Then, in interpreting \(\alpha\) as a variable in terms of the variation of any determining function, we shall be led into errors unless we confine ourselves to predicative determining functions. These errors especially arise in the transition to total variation (cf. pp. 15, 16). Accordingly \[ f\alpha =.(\exists \psi ).\phi !x\equiv_{x}\psi !x.f\{\psi !\hat{z}\}\quad \text{Df.} \] It is the peculiarity of a definition of the use of a single letter [viz. \(\alpha\)] for a variable incomplete symbol that it, though in a sense a real variable, occurs only in the definiendum, while "\(\phi \)," though a real variable, occurs only in the definiens.
Thus "\(f\hat{\alpha }\)" stands for \[ “(\exists \psi ).\hat{\phi }!x\equiv_{x}\psi !x.f\{\psi !\hat{z}\},” \] and "(\(\alpha).f\alpha\)" stands for \[ “(\phi ):(\exists \psi ).\phi !x\equiv_{x}\psi !x.f\{\psi !\hat{z}\}. ” \] Accordingly, in mathematical reasoning, we can dismiss the whole apparatus of functions and think only of classes as "quasi-things," capable of immediate representation by a single name. The advantages are two-fold: (1) classes are determined by their membership, so that to one set of members there is one class, (2) the "type" of a class is entirely defined by the type of its members.
Also a predicative function of a class can be defined thus \[ f!\alpha =.(\exists \psi ).\phi !x\equiv_{x}\psi !x.f!\{\psi !\hat{z}\}\quad \text{Df.} \] Thus a predicative function of a class is always a predicative function of any predicative determining function of the class, though the converse does not hold.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-CLASS-CONSEQUENCES-PP81B-84 -/

/- PM-FORMAL-GLOSS
This source-critical historical prose introduces no Lean declaration.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-RELATIONS-PP85-86A
(3) Relations. With regard to relations, we have a theory strictly analogous to that which we have just explained as regards classes. Relations in extension, like classes, are incomplete symbols. We require a division of functions of two variables into predicative and non-predicative functions, again for reasons which have been explained in Chapter II. We use the notation "\(\phi !(x,y)\)" for a predicative function of \(x\) and \(y\).
We use "\(\phi !(\hat{x},\hat{y})\)" for the function as opposed to its values; and we use "\(\hat{x}\hat{y} \phi (x,y)\)" for the relation (in extension) determined by \(\phi(x,y)\). We put \[ f\{\hat{x}\hat{y} \phi(x,y)\}.=\colon(\exists \psi)\colon \phi(x,y).\equiv_{x,y}.\psi !(x,y)\colon f\{\psi!(\hat{x},\hat{y})\} \quad \text{Df}. \] Thus even when \(f\{\psi !(\hat{x},\hat{y})\}\) is not an extensional function of \(\psi\), \(f\{\hat{x}\hat{y} \phi(x,y)\}\) is an extensional function of \(\phi\). Hence, just as in the case of classes, we deduce \[ \vdash \colon\ldotp\hat{x}\hat{y} \phi(x,y)=\hat{x}\hat{y} \psi(x,y).\equiv\colon \phi(x,y).\equiv_{x,y}.\psi(x,y), \] i.e. a relation is determined by its extension, and vice versa.
On the analogy of the definition of "\(x \in \psi!\hat{z}\)," we put \[ x\{\psi!(\hat{x},\hat{y})\}y.=.\psi !(x,y) \quad \text{Df}. \]
This definition, like that of "\(x \in \psi!\hat{z}\)," is not introduced for its own sake, but in order to give a meaning to \[ x\{\hat{x}\hat{y} \phi(x,y)\}y. \] This meaning, in virtue of our definitions, is \[ \begin{array}{l} &(\exists \psi)\colon \phi(x,y).\equiv_{x,y}.\psi !(x,y)\colon x\{\psi !(\hat{x},\hat{y})\}y,\\ \textit{i.e.}\quad &(\exists \psi)\colon \phi(x,y).\equiv_{x,y}. \psi !(x,y)\colon \psi !(x,y), \end{array} \] and this, in virtue of the axiom of reducibility \[ “(\exists \psi)\colon \phi(x,y).\equiv_{x,y}. \psi !(x,y),” \] is equivalent to \(\phi(x,y)\).
Thus we have always \[ \vdash \colon x\{\hat{x}\hat{y} \phi(x,y)\}y.\equiv.\phi(x,y). \]
Whenever the determining function of a relation is not relevant, we may replace \(\hat{x}\hat{y} \phi (x,y)\) by a single capital letter. In virtue of the propositions given above, \[ \begin{array}{l} &\vdash \colon\ldotp R=S.\equiv \colon xRy.\equiv_{x,y}.xSy,\\ &\vdash \colon\ldotp R=\hat{x}\hat{y} \phi(x,y).\equiv \colon xRy.\equiv_{x,y}.\phi(x,y),\\ \text{and}\quad &\vdash .R=\hat{x}\hat{y}(xRy). \end{array} \]
Classes of relations, and relations of relations, can be dealt with as classes of classes were dealt with above.
Just as a class must not be capable of being or not being a member of itself, so a relation must not be referent or relatum with respect to itself. This turns out to be equivalent to the assertion that \(\phi!(\hat{x},\hat{y})\) cannot significantly be either of the arguments \(x\) or \(y\) in \(\phi!(x,y)\). This principle, again, results from the limitation to the possible arguments to a function explained at the beginning of Chapter II.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-RELATIONS-PP85-86A -/

/- PM-FORMAL-GLOSS
This source-critical historical prose introduces no Lean declaration.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-INCOMPLETE-SYMBOLS-SUMMARY-PP86B-88
We may sum up this whole discussion on incomplete symbols as follows.
The use of the symbol "(\({℩}x)(\phi x)\)" as if in "\(f({℩}x)(\phi x)\)" it directly represented an argument to the function \(f\hat{z}\) is rendered possible by the theorems \[ \begin{array}{l} \vdash \colon\ldotp \text{E}!(℩x)(\phi x).\supset \colon (x).fx.\supset.f(℩x)(\phi x),\\ \vdash \colon(℩x)(\phi x)=(℩x)(\psi x).\supset.f(℩x)(\phi x)\equiv f(℩x)(\psi x),\\ \vdash \colon \text{E}!(℩x)(\phi x).\supset.(℩x)(\phi x)=(℩x)(\phi x),\\ \vdash \colon(℩x)(\phi x)=(℩x)(\psi x).\equiv.(℩x)(\psi x)=(℩x)(\phi x),\\ \vdash \colon(℩x)(\phi x)=(℩x)(\psi x).(℩x)(\psi x)=(℩x)(\chi x).\supset.(℩x)(\phi x)=(℩x)(\chi x). \end{array} \]
The use of the symbol "\(\hat{x}(\phi x)\)" (or of a single letter, such as \(\alpha\), to represent such a symbol) as if, in "\(f\{\hat{x}(\phi x)\}\)," it directly represented an argument \(\alpha\) to a function \(f\hat{\alpha}\), is rendered possible by the theorems \[ \begin{array}{l} \vdash \colon(\alpha).f\alpha.\supset.f\{\hat{x}(\phi x)\},\\ \vdash \colon \hat{x}(\phi x)=\hat{x}(\psi x).\supset.f\{\hat{x}(\phi x)\}\equiv f\{\hat{x}(\psi x)\},\\ \vdash .\hat{x}(\phi x)=\hat{x}(\phi x),\\ \vdash \colon \hat{x}(\phi x)=\hat{x}(\psi x).\equiv.\hat{x}(\psi x)=\hat{x}(\phi x),\\ \vdash \colon \hat{x}(\phi x)=\hat{x}(\psi x).\hat{x}(\psi x)=\hat{x}(\chi x).\supset.\hat{x}(\phi x)=\hat{x}(\chi x). \end{array} \]
Throughout these propositions the types must be supposed to be properly adjusted, where ambiguity is possible.
The use of the symbol "\(\hat{x}\hat{y}\{\phi (x,y)\}\)"(or of a single letter, such as \(R\), to represent such a symbol) as if, in "\(f\{\hat{x}\hat{y} \phi (x,y)\}\)," it directly represented an argument \(R\) to a function \(f\hat{R}\), is rendered possible by the theorems \[ \begin{array}{l} \vdash \colon(R).fR.\supset.f\{\hat{x}\hat{y} \phi(x,y)\},\\ \vdash \colon \hat{x}\hat{y} \phi(x,y)=\hat{x}\hat{y} \psi(x,y).\supset.f\{\hat{x}\hat{y}\phi (x,y)\}\equiv f\{\hat{x}\hat{y} \psi(x,y)\},\\ \vdash .\hat{x}\hat{y} \phi(x,y)=\hat{x}\hat{y} \phi(x,y),\\ \vdash \colon \hat{x}\hat{y} \phi(x,y)=\hat{x}\hat{y} \psi(x,y).\equiv.\hat{x}\hat{y} \psi(x,y)=\hat{x}\hat{y} \phi(x,y),\\ \vdash \colon \hat{x}\hat{y} \phi(x,y)=\hat{x}\hat{y} \psi(x,y).\hat{x}\hat{y}\psi(x,y)=\hat{x}\hat{y} \chi(x,y).\\ \qquad\qquad\qquad\qquad\qquad\qquad\qquad\quad\supset.\hat{x}\hat{y} \phi(x,y)=\hat{x}\hat{y} \chi(x,y). \end{array} \] Throughout these propositions the types must be supposed to be properly adjusted where ambiguity is possible.
It follows from these three groups of theorems that these incomplete symbols are obedient to the same formal rules of identity as symbols which directly represent objects, so long as we only consider the equivalence of the resulting variable (or constant) values of propositional functions and not their identity. This consideration of the identity of propositions never enters into our formal reasoning.
Similarly the limitations to the use of these symbols can be summed up as follows. In the case of (\({℩}x)(\phi x)\), the chief way in which its incompleteness is relevant is that we do not always have \[ (x).fx.\supset.f({℩}x)(\phi x), \] i.e. a function which is always true may nevertheless not be true of (\({℩}x)(\phi x)\). This is possible because \(f({℩}x)(\phi x)\) is not a value of \(f\hat{x}\), so that even when all values of \(f\hat{x}\) are true, \(f({℩}x)(\phi x)\) may not be true. This happens when (\({℩}x)(\phi x)\) does not exist. Thus for example we have (\(x).x=x\), but we do not have \[ \begin{array}{l} &\text{the round square} = \text{the round square}.\\ \text{The inference} &\qquad\qquad\quad(x).fx.\supset.f({℩}x)(\phi x) \end{array} \] is only valid when \(\text{E}!({℩}x)(\phi x)\). As soon as we know \(\text{E}!({℩}x)(\phi x)\), the fact that (\({℩}x)(\phi x\)) is an incomplete symbol becomes irrelevant so long as we confine ourselves to truth-functions of whatever proposition is its scope. But even when \(\text{E}!({℩}x)(\phi x)\), the incompleteness of (\({℩}x)(\phi x)\) may be relevant when we pass outside truth-functions. For example, George IV wished to know whether Scott was the author of Waverley, i.e. he wished to know whether a proposition of the form "\(c=({℩}x)(\phi x)\)" was true. But there was no proposition of the form "\(c=y\)" concerning which he wished to know if it was true.
In regard to classes, the relevance of their incompleteness is somewhat different. It may be illustrated by the fact that we may have \[ \begin{array}{l} &\hat{z}(\phi z)=\psi !\hat{z}.\hat{z}(\phi z)=\chi !\hat{z}\\ \text{without having} &\qquad\qquad\quad \psi!\hat{z}=\chi!\hat{z}. \end{array} \] For, by a direct application of the definitions, we find that \[ \vdash \colon\hat{z}(\phi z)=\psi !\hat{z}.\equiv.\phi x\equiv_{x}\psi !x. \] Thus we shall have \[ \vdash \colon \phi x\equiv_{x}\psi !x.\phi x\equiv_{x}\chi !x.\supset.\hat{z}(\phi z)=\psi !\hat{z}.\hat{z}(\phi z)=\chi !\hat{z}, \] but we shall not necessarily have \(\psi!\hat{z} = \chi !\hat{z}\) under these circumstances, for two functions may well be formally equivalent without being identical; for example, \[ x=\text{Scott}.\equiv_{x}.x=\text{the author of Waverley}, \]
but the function "\(\hat{z}\)=the author of Waverley" has the property that George IV wished to know whether its value with the argument "Scott" was true, whereas the function "\(\hat{z}\)=Scott" has no such property, and therefore the two functions are not identical. Hence there is a propositional function, namely \[ x=y.x=z.\supset.y=z, \] which holds without any exception, and yet does not hold when for \(x\) we substitute a class, and for \(y\) and \(z\) we substitute functions. This is only possible because a class is an incomplete symbol, and therefore "\(\hat{z}(\phi z)=\psi !\hat{z}\)" is not a value of "\(x=y\)."
It will be observed that "\(\theta!\hat{z}=\psi !\hat{z}\)" is not an extensional function of \(\psi!\hat{z}\). Thus the scope of \(\hat{z}(\phi z\)) is relevant in interpreting the product \[ \hat{z}(\phi z)=\psi !\hat{z}.\hat{z}(\phi z)=\chi !\hat{z}. \] If we take the whole of the product as the scope of \(\hat{z}(\phi z)\), the product is equivalent to \[ \begin{array}{l} &(\exists \theta)\colon \phi x\equiv_{x}\theta !x.\theta !\hat{z}=\psi !\hat{z}.\theta!\hat{z}=\chi !\hat{z},\\ \text{and this}\, \textit{does}\, \text{imply} &\psi !\hat{z}=\chi !\hat{z}. \end{array} \]
We may say generally that the fact that \(\hat{z}(\phi z\)) is an incomplete symbol is not relevant so long as we confine ourselves to extensional functions of functions, but is apt to become relevant for other functions of functions.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-INCOMPLETE-SYMBOLS-SUMMARY-PP86B-88 -/

/- PM-FORMAL-GLOSS
This source-critical historical prose introduces no Lean declaration.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-33
[33]
As explained in Chapter I (pp. 25, 26), "\(x \in \alpha\)" means "\(x\) is a member of the class \(\alpha\)," or, more shortly, "\(x\) is an \(\alpha\)." The definition of this expression in terms of our theory of classes will be given shortly.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-33 -/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-34
[34]
This is the second of the contradictions discussed at the end of Chapter II.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-34 -/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-35
[35]
The use of a single letter, such as \(\alpha\) or \(\beta\), to represent a variable class, will be further explained shortly.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-35 -/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-36
[36]
This definition raises certain questions as to the two senses of a relation, which are dealt with in *21.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-36 -/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-37
[37]
Cf. p. 8.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-37 -/

end PM.FirstEdition.Volume1.Introduction.Chapter3
