namespace PM.FirstEdition.Volume1.Introduction.Chapter3

/-! # Chapter III, pages 69–78

Canonical edition: first edition, volume I (1910), pp. 69–78, scan leaves
91–100. This scan-collated verbal-diplomatic reflow opens Chapter III.
Page-local notes 29–32 are independent canonical blocks. The confirmed
first-impression error in formula (4) on page 74 is retained below and recorded
in the external apparatus; errors confined to digital witnesses are excluded.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-DESCRIPTIONS-PP69-71
CHAPTER III.
INCOMPLETE SYMBOLS.
(1) Descriptions. By an "incomplete" symbol we mean a symbol which is not supposed to have any meaning in isolation, but is only defined in certain contexts. In ordinary mathematics, for example, \(\frac{d}{dx}\) and \(\int_{a}^{b}\) are incomplete symbols: something has to be supplied before we have anything significant. Such symbols have what may be called a "definition in use." Thus if we put \[ \nabla^{2} = \frac{\partial^{2}}{{\partial}x^{2}} + \frac{\partial^{2}}{{\partial}y^{2}} + \frac{\partial^{2}}{{\partial}z^{2}} \quad \text{Df}\text{,} \] we define the use of \(\nabla^{2}\), but \(\nabla^{2}\) by itself remains without meaning. This distinguishes such symbols from what (in a generalized sense) we may call proper names: "Socrates," for example, stands for a certain man, and therefore has a meaning by itself, without the need of any context. If we supply a context, as in "Socrates is mortal," these words express a fact of which Socrates himself is a constituent: there is a certain object, namely Socrates, which does have the property of mortality, and this object is a constituent of the complex fact which we assert when we say "Socrates is mortal." But in other cases, this simple analysis fails us. Suppose we say: "The round square does not exist." It seems plain that this is a true proposition, yet we cannot regard it as denying the existence of a certain object called "the round square." For if there were such an object, it would exist: we cannot first assume that there is a certain object, and then proceed to deny that there is such an object. Whenever the grammatical subject of a proposition can be supposed not to exist without rendering the proposition meaningless, it is plain that the grammatical subject is not a proper name, i.e. not a name directly representing some object. Thus in all such cases, the proposition must be capable of being so analysed that what was the grammatical subject shall have disappeared. Thus when we say "the round square does not exist," we may, as a first attempt at such analysis, substitute "it is false that there is an object \(x\) which is both round and square." Generally, when "the so-and-so" is said not to exist, we have a proposition of the form \[ \unicode{x201c}{\sim}\text{E}!({℩}x)({\phi}x),\unicode{x201d} \]
\[ \textit{i.e.} \quad {\sim}\{(\exists c) \colon \phi x \ldotp \equiv_{x} \ldotp x = c\}\text{,} \]
or some equivalent. Here the apparent grammatical subject \(({℩}x)({\phi}x)\) has completely disappeared; thus in "\({\sim}\text{E}!({℩}x)({\phi}x)\)," \(({℩}x)({\phi}x)\) is an incomplete symbol.
By an extension of the above argument, it can easily be shown that \(({℩}x)({\phi}x)\) is always an incomplete symbol. Take, for example, the following proposition: "Scott is the author of Waverley." [Here "the author of Waverley" is \(({℩}x)(x ~\text{wrote Waverley})\).] This proposition expresses an identity; thus if "the author of Waverley" could be taken as a proper name, and supposed to stand for some object \(c\), the proposition would be "Scott is \(c\)." But if \(c\) is any one except Scott, this proposition is false; while if \(c\) is Scott, the proposition is "Scott is Scott," which is trivial, and plainly different from "Scott is the author of Waverley." Generalizing, we see that the proposition \[ a = ({℩}x)({\phi}x) \] is one which may be true or may be false, but is never merely trivial, like \(a = a\); whereas, if \(({℩}x)({\phi}x)\) were a proper name, \(a = ({℩}x)({\phi}x)\) would necessarily be either false or the same as the trivial proposition \(a = a\). We may express this by saying that \(a = ({℩}x)({\phi}x)\) is not a value of the propositional function \(a = y\), from which it follows that \(({℩}x)({\phi}x)\) is not a value of \(y\). But since \(y\) may be anything, it follows that \(({℩}x)({\phi}x)\) is nothing. Hence, since in use it has meaning, it must be an incomplete symbol.
It might be suggested that "Scott is the author of Waverley" asserts that "Scott" and "the author of Waverley" are two names for the same object. But a little reflection will show that this would be a mistake. For if that were the meaning of "Scott is the author of Waverley," what would be required for its truth would be that Scott should have been called the author of Waverley: if he had been so called, the proposition would be true, even if some one else had written Waverley; while if no one called him so, the proposition would be false, even if he had written Waverley. But in fact he was the author of Waverley at a time when no one called him so, and he would not have been the author if every one had called him so but some one else had written Waverley. Thus the proposition "Scott is the author of Waverley" is not a proposition about names, like "Napoleon is Bonaparte"; and this illustrates the sense in which "the author of Waverley" differs from a true proper name.
Thus all phrases (other than propositions) containing the word the (in the singular) are incomplete symbols: they have a meaning in use, but not in isolation. For "the author of Waverley" cannot mean the same as "Scott," or "Scott is the author of Waverley" would mean the same as "Scott is Scott," which it plainly does not; nor can "the author of Waverley" mean anything other than "Scott," or "Scott is the author of Waverley" would be false. Hence "the author of Waverley" means nothing.
It follows from the above that we must not attempt to define "(\({℩}x)({\phi}x)\)," but must define the uses of this symbol, i.e. the propositions in whose symbolic expression it occurs. Now in seeking to define the uses of this symbol, it is important to observe the import of propositions in which it occurs. Take as an illustration: "The author of Waverley was a poet." This implies (1) that Waverley was written, (2) that it was written by one man, and not in collaboration, (3) that the one man who wrote it was a poet. If any one of these fails, the proposition is false. Thus "the author of 'Slawkenburgius on Noses' was a poet" is false, because no such book was ever written; "the author of 'The Maid's Tragedy' was a poet" is false, because this play was written by Beaumont and Fletcher jointly. These two possibilities of falsehood do not arise if we say "Scott was a poet." Thus our interpretation of the uses of \(({℩}x)({\phi}x)\) must be such as to allow for them. Now taking \({\phi}x\) to replace "\(x\) wrote Waverley," it is plain that any statement apparently about (\({℩}x)({\phi}x)\) requires (1) (\(\exists x).({\phi}x)\) and (2) \({\phi}x . {\phi}y . \supset_{x, y} . x = y\); here (1) states that at least one object satisfies \({\phi}x\), while (2) states that at most one object satisfies \({\phi}x\). The two together are equivalent to \[ \begin{align} (\exists c) \colon &{\phi}x \ldotp \equiv_{x} \ldotp x = c\text{,}\\ \text{which we defined as}\qquad &\text{E}!({℩}x)({\phi}x). \end{align} \] Thus "\(\text{E}!({℩}x)({\phi}x)\)" must be part of what is affirmed by any proposition about (\({℩}x)({\phi}x)\). If our proposition is \(f\{({℩}x)({\phi}x)\}\), what is further affirmed is \(fc\), if \({\phi}x \ldotp \equiv_{x} \ldotp x = c\). Thus we have \[ f\{({℩}x)({\phi}x)\} \ldotp = : (\exists c) : {\phi}x . \equiv_{x} . x = c:fc \quad \text{Df}\text{,} \] i.e. "the \(x\) satisfying \({\phi}x\) satisfies \(fx\)" is to mean: "There is an object \(c\) such that \({\phi}x\) is true when, and only when, \(x\) is \(c\), and \(fc\) is true," or, more exactly: "There is a \(c\) such that '\({\phi}x\)' is always equivalent to '\(x\) is \(c\),' and \(fc\)." In this, "\(({℩}x)({\phi}x)\)" has completely disappeared; thus "\(({℩}x)({\phi}x)\)" is merely symbolic, and does not directly represent an object, as single small Latin letters are assumed to do.
The proposition "\(a = ({℩}x)({\phi}x)\)" is easily shown to be equivalent to "\({\phi}x . \equiv_{x} . x = a\)." For, by the definition, it is \[ (\exists c) : {\phi}x . \equiv_{x} . x = c \colon a = c\text{,} \] i.e. "there is a \(c\) for which \({\phi}x . \equiv_{x} . x = c\), and this \(c\) is \(a\)," which is equivalent to "\({\phi}x . \equiv_{x} . x = a\)." Thus "Scott is the author of Waverley" is equivalent to: \[ \unicode{x201c}\unicode{x2018}x\,\, \text{wrote Waverley}\unicode{x2019}\,\, \text{is always equivalent to}\,\, \unicode{x2018}x\,\, \text{is Scott},\unicode{x2019}\unicode{x201d} \] i.e. "\(x\) wrote Waverley" is true when \(x\) is Scott and false when \(x\) is not Scott.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-DESCRIPTIONS-PP69-71 -/

/- PM-FORMAL-GLOSS
The historical analysis of descriptions is documentary and introduces no Lean declaration.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-SCOPE-TWO-DESCRIPTIONS-PP72-75A
Thus although "\(({℩}x)({\phi}x)\)" has no meaning by itself, it may be substituted for \(y\) in any propositional function \(fy\), and we get a significant proposition, though not a value of \(fy\).
When \(f\{({℩}x)(\phi x)\}\), as above defined, forms part of some other proposition, we shall say that (\({℩}x)(\phi x)\) has a secondary occurrence. When (\({℩}x)(\phi x)\) has a secondary occurrence, a proposition in which it occurs may be true even when (\({℩}x)(\phi x)\) does not exist. This applies, e.g. to the proposition: "There is no such person as the King of France." We may interpret this as \[ \begin{array}{l} &\sim{\{\text{E}!({℩}x)(\phi x)\}},\\ \text{or as}\quad &\sim{\{(\exists c) . c = ({℩}x)(\phi x)\}}, \end{array} \] if "\(\phi x\)" stands for "\(x\) is King of France." In either case, what is asserted is that a proposition \(p\) in which (\({℩}x)(\phi x)\) occurs is false, and this proposition \(p\) is thus part of a larger proposition. The same applies to such a proposition as the following: "If France were a monarchy, the King of France would be of the House of Orleans."
It should be observed that such a proposition as \[ \sim{f\{({℩}x)(\phi x)\}} \] is ambiguous; it may deny \(f\{({℩}x)(\phi x)\}\), in which case it will be true if (\({℩}x)(\phi x)\) does not exist, or it may mean \[ (\exists c) \colon \phi x . \equiv_{x} . x = c \colon \sim{fc}, \] in which case it can only be true if (\({℩}x)(\phi x)\) exists. In ordinary language, the latter interpretation would usually be adopted. For example, the proposition "the King of France is not bald" would usually be rejected as false, being held to mean "the King of France exists and is not bald," rather than "it is false that the King of France exists and is bald." When (\({℩}x)(\phi x)\) exists, the two interpretations of the ambiguity give equivalent results; but when (\({℩}x)(\phi x)\) does not exist, one interpretation is true and one is false. It is necessary to be able to distinguish these in our notation; and generally, if we have such propositions as \[ \begin{array}{l} \psi({℩}x)(\phi x) . \supset . p,\\ p . \supset . \psi({℩}x)(\phi x),\\ \psi({℩}x)(\phi x) . \supset . \chi({℩}x)(\phi x), \end{array} \]
and so on, we must be able by our notation to distinguish whether the whole or only part of the proposition concerned is to be treated as the "\(f\{({℩}x)(\phi x)\}\)" of our definition. For this purpose, we will put "[(\(℩x)(\phi x)\)]" followed by dots at the beginning of the part (or whole) which is to be taken as \(f({℩}x)(\phi x)\), the dots being sufficiently numerous to bracket off the \(f({℩}x)(\phi x)\); i.e. \(f({℩}x)(\phi x)\) is to be everything following the dots until we reach an equal number of dots not signifying a logical product, or a greater number signifying a logical product, or the end of the sentence, or the end of a bracket enclosing "[(\({℩}x)(\phi x)\)]." Thus \[ \begin{array}{l} &[({℩}x)(\phi x)] . \psi({℩}x)(\phi x) . \supset . p\\ \text{will mean} \qquad &(\exists c) \colon \phi x . \equiv_{x} . x = c \colon \psi c \colon \supset . p,\\ \text{but}\qquad &[({℩}x)(\phi x)] \colon \psi({℩}x)(\phi x) . \supset . p\\ \text{will mean}\qquad &(\exists c) \colon \phi x . \equiv_{x} . x = c \colon \psi c . \supset . p. \end{array} \] It is important to distinguish these two, for if (\({℩}x)(\phi x)\) does not exist, the first is true and the second false. Again \[ \begin{array}{l} &[({℩}x)(\phi x)] . \sim{\psi({℩}x)(\phi x)}\\ \text{will mean} \qquad &(\exists c) \colon \phi x . \equiv_{x} . x = c \colon \sim{\psi c},\\ \text{while}\qquad &\sim{\{[({℩}x)(\phi x)] . \psi({℩}x)(\phi x)\}}\\ \text{will mean}\qquad &\sim{\{(\exists c) \colon \phi x . \equiv_{x} . x = c \colon \sim{\psi c}\}}. \end{array} \] Here again, when (\({℩}x)(\phi x)\) does not exist, the first is false and the second true.
In order to avoid this ambiguity in propositions containing (\({℩}x)(\phi x)\), we amend our definition, or rather our notation, putting \[ [({℩}x)(\phi x)] . f({℩}x)(\phi x) . = \colon (\exists c) \colon \phi x . \equiv_{x} . x = c \colon fc \quad \text{Df}. \] By means of this definition, we avoid any doubt as to the portion of our whole asserted proposition which is to be treated as the "\(f({℩}x)(\phi x)\)" of the definition. This portion will be called the scope of (\({℩}x)(\phi x)\). Thus in \[ [({℩}x)(\phi x)] . f({℩}x)(\phi x) . \supset . p \] the scope of (\({℩}x)(\phi x)\) is \(f({℩}x)(\phi x)\); but in \[ \begin{array}{l} &[({℩}x)(\phi x)] \colon f({℩}x)(\phi x) . \supset . p\\ \text{the scope is} \qquad &f({℩}x)(\phi x) . \supset . p;\\ \text{in} \qquad &\sim{\{[({℩}x)(\phi x)] . f({℩}x)(\phi x)\}} \end{array} \] the scope is \(f({℩}x)(\phi x)\); but in \[ \begin{array}{l} &[({℩}x)(\phi x)] . \sim{f({℩}x)(\phi x)}\\ \text{the scope is} \qquad &\sim{f({℩}x)(\phi x)}. \end{array} \]
It will be seen that when (\({℩}x)(\phi x)\) has the whole of the proposition concerned for its scope, the proposition concerned cannot be true unless \(\text{E} !({℩}x)(\phi x)\); but when (\({℩}x)(\phi x)\) has only part of the proposition concerned for its scope, it may often be true even when (\({℩}x)(\phi x)\) does not exist. It will be seen further that when \(\text{E} !({℩}x)(\phi x)\), we may enlarge or diminish the scope of (\({℩}x)(\phi x)\) as much as we please without altering the truth-value of any proposition in which it occurs.
If a proposition contains two descriptions, say (\({℩}x)(\phi x)\) and (\({℩}x)(\psi x)\), we have to distinguish which of them has the larger scope, i.e. we have to distinguish \[ \begin{array}{l} \text{(1)}\qquad [({℩}x)(\phi x)] \colon [({℩}x)(\psi x)] . f{({℩}x)(\phi x), ({℩}x)(\psi x)},\\ \text{(2)}\qquad [({℩}x)(\psi x)] \colon [({℩}x)(\phi x)] . f{({℩}x)(\phi x), ({℩}x)(\psi x)}. \end{array} \]
The first of these, eliminating (\({℩}x)(\phi x)\), becomes \[ \text{(3)}\qquad (\exists c) \colon \phi x.\equiv_{x}.x = c\colon [({℩}x)(\psi x)].f\{c, ({℩}x)(\psi x)\}, \] which, eliminating (\({℩}x)(\phi x)\) becomes \[ \text{(4)}\qquad (\exists c) \colon\ldotp \phi x.\equiv_{x}.x = c\colon\ldotp (\exists d) \colon \psi x.\equiv_{x}.x = c \colon f(c, d), \] and the same proposition results if, in (1), we eliminate first (\({℩}x)(\psi x)\) and then (\({℩}x)(\phi x)\). Similarly (2) becomes, when (\({℩}x)(\phi x)\) and (\({℩}x)(\psi x)\) are eliminated, \[ \text{(5)}\qquad (\exists d)\colon\ldotp \psi x.\equiv_{x}.x = d\colon\ldotp(\exists c) \colon \phi x.\equiv_{x}.x = c\colon f(c, d). \]
(4) and (5) are equivalent, so that the truth-value of a proposition containing two descriptions is independent of the question which has the larger scope.
It will be found that, in most cases in which descriptions occur, their scope is, in practice, the smallest proposition enclosed in dots or other brackets in which they are contained. Thus for example \[ [({℩}x)(\phi x)].\psi({℩}x)(\phi x). \supset . [({℩}x)(\phi x)].\chi({℩}x)(\phi x) \] will occur much more frequently than \[ [({℩}x)(\phi x)] \colon \psi({℩}x)(\phi x) . \supset . \chi({℩}x)(\phi x). \] For this reason it is convenient to decide that, when the scope of an occurrence of (\({℩}x)(\phi x)\) is the smallest proposition, enclosed in dots or other brackets, in which the occurrence in question is contained, the scope need not be indicated by "[(\({℩}x)(\phi x)\)]." Thus e.g. \[ \begin{array}{l} &p.\supset.a = ({℩}x)(\phi x)\\ \text{will mean}\qquad &p.\supset.[({℩}x)(\phi x)].a = ({℩}x)(\phi x);\\ \text{and}\qquad &p.\supset.(\exists a).a = ({℩}x)(\phi x)\\ \text{will mean}\qquad &p.\supset.(\exists a).[({℩}x)(\phi x)].a = ({℩}x)(\phi x);\\ \text{and}\qquad &p.\supset.a \neq ({℩}x)(\phi x)\\ \text{will mean}\qquad &p.\supset.[({℩}x)(\phi x)].\sim{\{a = ({℩}x)(\phi x)\}};\\ \text{but}\qquad &p.\supset.\sim{\{a = ({℩}x)(\phi x)}\}\\ \text{will mean}\qquad &p.\supset.\sim{\{[({℩}x)(\phi x)].a = ({℩}x)(\phi x)}\}. \end{array} \]
This convention enables us, in the vast majority of cases that actually occur, to dispense with the explicit indication of the scope of a descriptive symbol; and it will be found that the convention agrees very closely with the tacit conventions of ordinary language on this subject. Thus for example, if "(\({℩}x)(\phi x)\)" is "the so-and-so," "\(a \neq ({℩}x)(\phi x)\)" is to be read "\(a\) is not the so-and-so," which would ordinarily be regarded as implying that "the so-and-so" exists; but "\({\sim}\{a=({℩}x)(\phi x)\}\)" is to be read "it is not true that \(a\) is the so-and-so," which would generally be allowed to hold if "the so-and-so" does not exist. Ordinary language is, of course, rather loose and fluctuating in its implications on this matter; but subject to the requirement of definiteness, our convention seems to keep as near to ordinary language as possible.
In the case when the smallest proposition enclosed in dots or other brackets contains two or more descriptions, we shall assume, in the absence of any indication to the contrary, that one which typographically occurs earlier has a larger scope than one which typographically occurs later. Thus \[ \begin{array}{l} &({℩}x)(\phi x) = ({℩}x)(\psi x)\\ \text{will mean}\qquad &(\exists c)\colon \phi x.\equiv_{x}.x = c\colon [({℩}x)(\psi x)].c = ({℩}x)(\psi x),\\ \text{while}\qquad &({℩}x)(\psi x) = ({℩}x)(\phi x)\\ \text{will mean} &(\exists d)\colon \psi x.\equiv_{x}.x = d\colon[(℩x)(\phi x)].({℩}x)(\phi x) = d. \end{array} \]
PM-VERBATIM-END PM1:INTRODUCTION-CH3-SCOPE-TWO-DESCRIPTIONS-PP72-75A -/

/- PM-FORMAL-GLOSS
The printed scope notation and its examples remain source text; no modern semantic reconstruction is silently substituted.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-CLASSES-PP75B-78
These two propositions are easily shown to be equivalent.
(2) Classes. The symbols for classes, like those for descriptions, are, in our system, incomplete symbols: their uses are defined, but they themselves are not assumed to mean anything at all. That is to say, the uses of such symbols are so defined that, when the definiens is substituted for the definiendum, there no longer remains any symbol which could be supposed to represent a class. Thus classes, so far as we introduce them, are merely symbolic or linguistic conveniences, not genuine objects as their members are if they are individuals.
It is an old dispute whether formal logic should concern itself mainly with intensions or with extensions. In general, logicians whose training was mainly philosophical have decided for intensions, while those whose training was mainly mathematical have decided for extensions. The facts seem to be that, while mathematical logic requires extensions, philosophical logic refuses to supply anything except intensions. Our theory of classes recognizes and reconciles these two apparently opposite facts, by showing that an extension (which is the same as a class) is an incomplete symbol, whose use always acquires its meaning through a reference to intension.
In the case of descriptions, it was possible to prove that they are incomplete symbols. In the case of classes, we do not know of any equally definite proof, though arguments of more or less cogency can be elicited from the ancient problem of the One and the Many. It is not necessary for our purposes, however, to assert dogmatically that there are no such things as classes. It is only necessary for us to show that the incomplete symbols which we introduce as representatives of classes yield all the propositions for the sake of which classes might be thought essential. When this has been shown, the mere principle of economy of primitive ideas leads to the non-introduction of classes except as incomplete symbols.
To explain the theory of classes, it is necessary first to explain the distinction between extensional and intensional functions. This is effected by the following definitions:
The truth-value of a proposition is truth if it is true, and falsehood if it is false. (This expression is due to Frege.)
Two propositions are said to be equivalent when they have the same truth-value, i.e. when they are both true or both false.
Two propositional functions are said to be formally equivalent when they are equivalent with every possible argument, i.e. when any argument which satisfies the one satisfies the other, and vice versa. Thus "\(\hat{x}\) is a man" is formally equivalent to "\(\hat{x}\) is a featherless biped"; "\(\hat{x}\) is an even prime" is formally equivalent to "\(\hat{x}\) is identical with 2."
A function of a function is called extensional when its truth-value with any argument is the same as with any formally equivalent argument. That is to say, \(f(\phi ! \hat{z})\) is an extensional function of \(\phi ! \hat{z}\) if, provided \(\psi ! \hat{z}\) is formally equivalent to \(\phi ! \hat{z}\), \(f(\phi ! \hat{z})\) is equivalent to \(f(\psi ! \hat{z})\). Here the apparent variables \(\phi\) and \(\psi\) are necessarily of the type from which arguments can significantly be supplied to \(f\). We find no need to use as apparent variables any functions of non-predicative types; accordingly in the sequel all extensional functions considered are in fact functions of predicative functions.
A function of a function is called intensional when it is not extensional.
The nature and importance of the distinction between intensional and extensional functions will be made clearer by some illustrations. The proposition "'\(x\) is a man' always implies '\(x\) is a mortal'" is an extensional function of the function "\(\hat{x}\) is a man," because we may substitute, for "\(x\) is a man," "\(x\) is a featherless biped," or any other statement which applies to the same objects to which "\(x\) is a man" applies, and to no others. But the proposition "\(A\) believes that '\(x\) is a man' always implies '\(x\) is a mortal'" is an intensional function of "\(\hat{x}\) is a man," because \(A\) may never have considered the question whether featherless bipeds are mortal, or may believe wrongly that there are featherless bipeds which are not mortal. Thus even if "\(x\) is a featherless biped" is formally equivalent to "\(x\) is a man," it by no means follows that a person who believes that all men are mortal must believe that all featherless bipeds are mortal, since he may have never thought about featherless bipeds, or have supposed that featherless bipeds were not always men. Again the proposition "the number of arguments that satisfy the function \(\phi ! \hat{z}\) is \(n\)" is an extensional function of \(\phi ! \hat{z}\), because its truth or falsehood is unchanged if we substitute for \(\phi ! \hat{z}\) any other function which is true whenever \(\phi ! \hat{z}\) is true, and false whenever \(\phi ! \hat{z}\) is false. But the proposition "\(A\) asserts that the number of arguments satisfying \(\phi ! \hat{z}\) is n" is an intensional function of \(\phi ! \hat{z}\),
since, if \(A\) asserts this concerning \(\phi ! \hat{z}\), he certainly cannot assert it concerning all predicative functions that are equivalent to \(\phi ! \hat{z}\), because life is too short. Again, consider the proposition "two white men claim to have reached the North Pole." This proposition states "two arguments satisfy the function '\(\hat{x}\) is a white man who claims to have reached the North Pole.'" The truth or falsehood of this proposition is unaffected if we substitute for "\(\hat{x}\) is a white man who claims to have reached the North Pole" any other statement which holds of the same arguments, and of no others. Hence it is an extensional function. But the proposition "it is a strange coincidence that two white men should claim to have reached the North Pole," which states "it is a strange coincidence that two arguments should satisfy the function '\(\hat{x}\) is a white man who claims to have reached the North Pole,'" is not equivalent to "it is a strange coincidence that two arguments should satisfy the function '\(\hat{x}\) is Dr Cook or Commander Peary.'" Thus "it is a strange coincidence that \(\phi ! \hat{x}\) should be satisfied by two arguments" is an intensional function of \(\phi ! \hat{x}\).
The above instances illustrate the fact that the functions of functions with which mathematics is specially concerned are extensional, and that intensional functions of functions only occur where non-mathematical ideas are introduced, such as what somebody believes or affirms, or the emotions aroused by some fact. Hence it is natural, in a mathematical logic, to lay special stress on extensional functions of functions.
When two functions are formally equivalent, we may say that they have the same extension. In this definition, we are in close agreement with usage. We do not assume that there is such a thing as an extension: we merely define the whole phrase "having the same extension." We may now say that an extensional function of a function is one whose truth or falsehood depends only upon the extension of its argument. In such a case, it is convenient to regard the statement concerned as being about the extension. Since extensional functions are many and important, it is natural to regard the extension as an object, called a class, which is supposed to be the subject of all the equivalent statements about various formally equivalent functions. Thus e.g. if we say "there were twelve Apostles," it is natural to regard this statement as attributing the property of being twelve to a certain collection of men, namely those who were Apostles, rather than as attributing the property of being satisfied by twelve arguments to the function "\(\hat{x}\) was an Apostle." This view is encouraged by the feeling that there is something which is identical in the case of two functions which "have the same extension." And if we take such simple problems as "how many combinations can be made of \(n\) things?" it seems at first sight necessary that each "combination" should be a single object which can be counted as one. This, however, is certainly not necessary technically, and we see no reason to suppose that it is true
philosophically. The technical procedure by which the apparent difficulty is overcome is as follows.
We have seen that an extensional function of a function may be regarded as a function of the class determined by the argument-function, but that an intensional function cannot be so regarded. In order to obviate the necessity of giving different treatment to intensional and extensional functions of functions, we construct an extensional function derived from any function of a predicative function \(\psi !\hat{z}\), and having the property of being equivalent to the function from which it is derived, provided this function is extensional, as well as the property of being significant (by the help of the systematic ambiguity of equivalence) with any argument \(\phi \hat{z}\) whose arguments are of the same type as those of \(\psi !\hat{z}\). The derived function, written "\(f\{\hat{z}(\phi z)\}\)," is defined as follows: Given a function \(f(\psi ! \hat{z}\)), our derived function is to be "there is a predicative function which is formally equivalent to \(\phi \hat{z}\) and satisfies \(f\)." If \(\phi \hat{z}\) is a predicative function, our derived function will be true whenever \(f(\phi \hat{z}\)) is true. If \(f(\phi \hat{z}\)) is an extensional function, and \(\phi \hat{z}\) is a predicative function, our derived function will not be true unless \(f(\phi \hat{z}\)) is true; thus in this case, our derived function is equivalent to \(f(\phi \hat{z}\)). If \(f(\phi \hat{z}\)) is not an extensional function, and if \(\phi \hat{z}\) is a predicative function, our derived function may sometimes be true when the original function is false. But in any case the derived function is always extensional.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-CLASSES-PP75B-78 -/

/- PM-FORMAL-GLOSS
The incomplete-symbol account of classes is historical prose and adds no Lean axiom.
-/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-29
Cf. pp. 31, 32.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-29 -/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-30
We shall generally write "\(f({℩}x)({\phi}x)\)" rather than "\(f\{({℩}x)({\phi}x)\}\)" in future.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-30 -/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-31
Briefly, these arguments reduce to the following: If there is such an object as a class, it must be in some sense one object. Yet it is only of classes that many can be predicated. Hence, if we admit classes as objects, we must suppose that the same object can be both one and many, which seems impossible.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-31 -/

/- PM-VERBATIM-BEGIN PM1:INTRODUCTION-CH3-NOTE-32
Cf. p. 56.
PM-VERBATIM-END PM1:INTRODUCTION-CH3-NOTE-32 -/

/- PM-EDITORIAL
Formula (4) on printed page 74 retains “x = c” [sic]; the conjectural correction
“x = d” is supplied only in the apparatus. Seven errors belonging solely to
Wikisource or Project Gutenberg are likewise documented outside the canonical
bytes. The paragraph beginning at the foot of page 78 continues on page 79 and
is transcribed as one unit in Pages79To88.
-/

end PM.FirstEdition.Volume1.Introduction.Chapter3
